# zsh/oh-my-zsh boilerplate:
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="dbeef"
zstyle ':omz:update' mode disabled  # disable automatic updates
plugins=(docker)
source $ZSH/oh-my-zsh.sh

# https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
alias tmux="TERM=xterm-256color tmux"

# Enter tmux on startup:
# https://unix.stackexchange.com/questions/43601/how-can-i-set-my-default-shell-to-start-up-tmux
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
    exec tmux
fi

# Custom aliases in terminal:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line
bindkey -s '^o' 'nautilus . > /dev/null 2>&1 &\n'
bindkey -s '^f' 'grep -rnF . -e '
bindkey -s '^n' 'fe\n'
bindkey -s '^x' 'fcd\n'

# Enable <C-u>:
# https://stackoverflow.com/questions/3483604/which-shortcut-in-zsh-does-the-same-as-ctrl-u-in-bash
bindkey \^U backward-kill-line

# fzf aliases:
source ~/.fzf_aliases.sh
[ -f ~/.fzf_aliases.sh ] && source ~/.fzf_aliases.sh

# Set vim as default editor:
export VISUAL=vim
export EDITOR="$VISUAL"

# Typical places for binaries:
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/go/bin:$PATH
export PATH=$PATH:/usr/local/go/bin

# Aliases:
alias vi=vim
alias apps="cd ~/apps"
alias dev="cd ~/dev"
alias toolbox="cd ~/dev/ctf/toolbox"
alias toolchains="cd ~/toolchains"
alias r='cd $(git rev-parse --show-toplevel)'

# Terminal:
export TERMINAL=gnome-terminal

# History size:
export HISTSIZE=9999

# https://unix.stackexchange.com/questions/72086/ctrl-s-hangs-the-terminal-emulator
stty -ixon

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
