# zsh/oh-my-zsh boilerplate:
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="dbeef"
zstyle ':omz:update' mode disabled  # disable automatic updates
plugins=(docker fzf-zsh-plugin)
source $ZSH/oh-my-zsh.sh

# https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
alias tmux="TERM=xterm-256color tmux"

# Enter tmux on startup:
# https://unix.stackexchange.com/questions/43601/how-can-i-set-my-default-shell-to-start-up-tmux
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
    exec tmux
fi

# Distro-specific variables:
if grep -qi Microsoft /proc/version; then
    # WSL:
    alias open_file_explorer='explorer.exe .'
else
    alias open_file_explorer='nautilus .'
fi

# Keep in mind to call 'zle reset-prompt', otherwise have to always press enter after invoking the binding:
# https://stackoverflow.com/questions/62205627/using-bindkey-to-call-a-function-in-zsh-requires-pressing-enter-after-function-r

widget-open-file-explorer() {
    open_file_explorer
    zle reset-prompt
}

widget-find-file-with-string() {
    fzf_find_file_with_string
    zle reset-prompt
}

widget-find-file-with-name() {
    fzf_find_file_with_name
    zle reset-prompt
}

# Custom aliases in terminal:
autoload edit-command-line; zle -N edit-command-line
autoload widget-find-file-with-string; zle -N widget-find-file-with-string
autoload widget-find-file-with-name; zle -N widget-find-file-with-name
autoload widget-open-file-explorer; zle -N widget-open-file-explorer

bindkey '^e' edit-command-line
bindkey '^o' widget-open-file-explorer
bindkey '^f' widget-find-file-with-string
bindkey '^n' widget-find-file-with-name

# Enable <C-u>:
# https://stackoverflow.com/questions/3483604/which-shortcut-in-zsh-does-the-same-as-ctrl-u-in-bash
bindkey \^U backward-kill-line

# fzf aliases:
source ~/.fzf_aliases.sh
[ -f ~/.fzf_aliases.sh ] && source ~/.fzf_aliases.sh

# Set vim as default editor:
export VISUAL=vim
export EDITOR="$VISUAL"

# Typical places for binaries:
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/go/bin:$PATH
export PATH=$PATH:/usr/local/go/bin

# Aliases:
alias vi=vim
alias apps="cd ~/apps"
alias dev="cd ~/dev"
alias toolbox="cd ~/dev/ctf/toolbox"
alias toolchains="cd ~/toolchains"
alias r='cd $(git rev-parse --show-toplevel)'

# Terminal:
export TERMINAL=gnome-terminal

# History size:
export HISTSIZE=9999

# https://unix.stackexchange.com/questions/72086/ctrl-s-hangs-the-terminal-emulator
stty -ixon

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
